/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Clases.Accidentado;
import Clases.Incapacidad;
import Clases.Mina;
import Clases.PanelAccidentado;
import Clases.PanelIncapacidad;
import Clases.PanelMina;
import Clases.PanelPersona;
import Clases.PanelProduccion;
import Clases.Persona;
import Clases.Produccion;
import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author GEORGE
 */
public class Inicio extends javax.swing.JFrame {

    private final int CEDULA;
    private final String ROL;
    public boolean bandera = true;
    DefaultTableModel modelo = new DefaultTableModel();
    JTable tabAcc = new JTable();
    DefaultTableModel acci = new DefaultTableModel();

    /**
     * Creates new form Inicio1
     */
    public Inicio(int cedula, String rol) {
        this.CEDULA = cedula;
        this.ROL = rol;

        initComponents();

        this.setResizable(false);
        setLocationRelativeTo(this);
        verInfoAccidentadoBtn.setVisible(false);
        verInfoIncapacitadoBtn.setVisible(false);
        ArrayList<String> datosPer = Persona.consultar(cedula);

        usuarioTxt.setText(datosPer.get(6));
        rolTxt.setText(datosPer.get(5));
        nombreTxt.setText(datosPer.get(0) + " " + datosPer.get(1));

        if (rol.equalsIgnoreCase("secretaria")) {
            agregarMinaMenu.setEnabled(false);
        } else if (rol.equalsIgnoreCase("cochero")) {
            menuAgregar.setEnabled(false);
            informesMenu.setEnabled(false);
            buscarBtn.setEnabled(false);
            buscarTxt.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioTxt = new javax.swing.JTextField();
        rolTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        panelAgregar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProduccion = new javax.swing.JTable();
        accidentadoCheck = new javax.swing.JCheckBox();
        editarBtn = new javax.swing.JButton();
        incapacitadoCheck = new javax.swing.JCheckBox();
        verInfoIncapacitadoBtn = new javax.swing.JButton();
        verInfoAccidentadoBtn = new javax.swing.JButton();
        producionBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        buscarTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        autoCheck = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        informesMenu = new javax.swing.JMenu();
        produccionMenu = new javax.swing.JMenuItem();
        personalMenu = new javax.swing.JMenuItem();
        accidentadosMenu = new javax.swing.JMenuItem();
        incapacitadosMenu = new javax.swing.JMenuItem();
        menuAgregar = new javax.swing.JMenu();
        agregarPersonaMenu = new javax.swing.JMenuItem();
        agregarMinaMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuarioTxt.setEditable(false);
        usuarioTxt.setEnabled(false);

        rolTxt.setEditable(false);
        rolTxt.setEnabled(false);

        nombreTxt.setEditable(false);
        nombreTxt.setEnabled(false);

        tablaProduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProduccionMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaProduccionMouseReleased(evt);
            }
        });
        tablaProduccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaProduccionKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProduccion);

        accidentadoCheck.setText("Accidentado");
        accidentadoCheck.setEnabled(false);
        accidentadoCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accidentadoCheckMouseClicked(evt);
            }
        });
        accidentadoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accidentadoCheckActionPerformed(evt);
            }
        });

        editarBtn.setText("Editar datos");
        editarBtn.setEnabled(false);

        incapacitadoCheck.setText("Incapacitado");
        incapacitadoCheck.setEnabled(false);
        incapacitadoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incapacitadoCheckActionPerformed(evt);
            }
        });

        verInfoIncapacitadoBtn.setText("Ver info");
        verInfoIncapacitadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInfoIncapacitadoBtnActionPerformed(evt);
            }
        });

        verInfoAccidentadoBtn.setText("Ver info");
        verInfoAccidentadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInfoAccidentadoBtnActionPerformed(evt);
            }
        });

        producionBtn.setText("Agregar producción");
        producionBtn.setEnabled(false);
        producionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(verInfoAccidentadoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(verInfoIncapacitadoBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(accidentadoCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(incapacitadoCheck)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(producionBtn)
                .addGap(196, 196, 196))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accidentadoCheck)
                    .addComponent(editarBtn)
                    .addComponent(incapacitadoCheck)
                    .addComponent(producionBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verInfoIncapacitadoBtn)
                    .addComponent(verInfoAccidentadoBtn))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panelAgregar.addTab("Informes", jPanel1);
        panelAgregar.addTab("*", jTabbedPane1);

        buscarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarTxtKeyPressed(evt);
            }
        });

        jLabel1.setText("Buscar:");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        autoCheck.setSelected(true);
        autoCheck.setText("Auto busqueda");

        informesMenu.setText("Informes");

        produccionMenu.setText("Produccion");
        produccionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionMenuActionPerformed(evt);
            }
        });
        informesMenu.add(produccionMenu);

        personalMenu.setText("Personal");
        personalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalMenuActionPerformed(evt);
            }
        });
        informesMenu.add(personalMenu);

        accidentadosMenu.setText("Accidentados");
        accidentadosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accidentadosMenuActionPerformed(evt);
            }
        });
        informesMenu.add(accidentadosMenu);

        incapacitadosMenu.setText("Incapacitados");
        incapacitadosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incapacitadosMenuActionPerformed(evt);
            }
        });
        informesMenu.add(incapacitadosMenu);

        jMenuBar1.add(informesMenu);

        menuAgregar.setText("Agregar");

        agregarPersonaMenu.setText("Persona");
        agregarPersonaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPersonaMenuActionPerformed(evt);
            }
        });
        menuAgregar.add(agregarPersonaMenu);

        agregarMinaMenu.setText("Mina");
        agregarMinaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMinaMenuActionPerformed(evt);
            }
        });
        menuAgregar.add(agregarMinaMenu);

        jMenuBar1.add(menuAgregar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nombreTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rolTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAgregar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(autoCheck))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rolTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAgregar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalMenuActionPerformed
        // TODO add your handling code here:
        borrarRegistros();
        buscarPersonaPorMina();

    }//GEN-LAST:event_personalMenuActionPerformed

    private void produccionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionMenuActionPerformed
        // TODO add your handling code here:
        borrarRegistros();
        btnDisable();
        buscarProduccion();


    }//GEN-LAST:event_produccionMenuActionPerformed

    private void agregarPersonaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPersonaMenuActionPerformed
        // TODO add your handling code here:
        PanelPersona panelper = new PanelPersona();
        //panelAgregar.add(panelper);
        JOptionPane.showMessageDialog(produccionMenu, panelper);
    }//GEN-LAST:event_agregarPersonaMenuActionPerformed

    private void agregarMinaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMinaMenuActionPerformed
        // TODO add your handling code here:
        PanelMina panelMina = new PanelMina();
        //panelAgregar.add(panelMina);
        JOptionPane.showMessageDialog(produccionMenu, panelMina);
    }//GEN-LAST:event_agregarMinaMenuActionPerformed

    private void buscarTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTxtKeyPressed
        // TODO add your handling code here:

        if (autoCheck.isSelected()) {
            btnDisable();
            borrarRegistros();
            buscarPersona();

        }
    }//GEN-LAST:event_buscarTxtKeyPressed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        // TODO add your handling code here:
        btnDisable();
        borrarRegistros();
        buscarPersona();
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void producionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producionBtnActionPerformed
        // TODO add your handling code here:
        PanelProduccion produccion = new PanelProduccion(cedulaSelect(), minaSelect());
        JOptionPane.showMessageDialog(produccionMenu, produccion);
    }//GEN-LAST:event_producionBtnActionPerformed

    private void accidentadoCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accidentadoCheckMouseClicked
        // TODO add your handling code here:
        if (accidentadoCheck.isSelected()) {

            //System.out.println(cedula);
            PanelAccidentado accidente = new PanelAccidentado(cedulaSelect());
            JOptionPane.showMessageDialog(null, accidente);
        } else {

        }
    }//GEN-LAST:event_accidentadoCheckMouseClicked

    private void tablaProduccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProduccionKeyReleased
        // TODO add your handling code here:
        btnDisable();
        if (tablaProduccion.getSelectedRow() >= 0) {
            btnEnable();
        }
    }//GEN-LAST:event_tablaProduccionKeyReleased

    private void tablaProduccionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProduccionMouseReleased
        // TODO add your handling code here:
        btnDisable();
        if (tablaProduccion.getSelectedRow() >= 0) {
            btnEnable();
        }
    }//GEN-LAST:event_tablaProduccionMouseReleased

    private void tablaProduccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProduccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaProduccionMouseClicked

    private void incapacitadoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incapacitadoCheckActionPerformed
        // TODO add your handling code here:
        if (incapacitadoCheck.isSelected()) {

            //System.out.println(cedula);
            PanelIncapacidad incapacidad = new PanelIncapacidad(cedulaSelect());
            JOptionPane.showMessageDialog(null, incapacidad);
        } else {

        }
    }//GEN-LAST:event_incapacitadoCheckActionPerformed

    private void accidentadoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accidentadoCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accidentadoCheckActionPerformed

    private void accidentadosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accidentadosMenuActionPerformed
        // TODO add your handling code here:
        borrarRegistros();
        buscarAccidentadosPorMina();
    }//GEN-LAST:event_accidentadosMenuActionPerformed

    private void incapacitadosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incapacitadosMenuActionPerformed
        // TODO add your handling code here:
        borrarRegistros();
        buscarIncapacitadosPorMina();
    }//GEN-LAST:event_incapacitadosMenuActionPerformed

    private void verInfoAccidentadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInfoAccidentadoBtnActionPerformed
        // TODO add your handling code here:
        informeAccidentePersona();
    }//GEN-LAST:event_verInfoAccidentadoBtnActionPerformed

    private void verInfoIncapacitadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInfoIncapacitadoBtnActionPerformed
        // TODO add your handling code here:
        informeIncapacidadPersona();
    }//GEN-LAST:event_verInfoIncapacitadoBtnActionPerformed

    private static int filPorMina() {
        ArrayList<String> minas = (ArrayList<String>) Mina.consultarMinas();

        String[] vecMinas = new String[(minas.size() / 2) + 2];

        int i = 0;
        int a = 0, b = 1;
        for (i = 0; i < vecMinas.length - 2; i++) {

            vecMinas[i] = minas.get(a) + " - " + minas.get(b);
            a += 2;
            b += 2;
        }

        vecMinas[i] = "Todas";
        vecMinas[i + 1] = "Seleccione";

        String opcion = (String) JOptionPane.showInputDialog(null, "Filtrar por mina", "Elegir", JOptionPane.QUESTION_MESSAGE, null, vecMinas, vecMinas[vecMinas.length - 1]);
        int idMina = 0;
        if (opcion.startsWith("Sel")) {
            JOptionPane.showMessageDialog(null, "Selecione una mina");
        } else if (opcion.startsWith("Tod")) {
            return idMina;
        } else {
            idMina = Integer.parseInt(opcion.substring(0, 1));
            //System.out.println(idMina);
        }
        return idMina;
    }

    private void btnDisable() {
        incapacitadoCheck.setEnabled(false);
        accidentadoCheck.setEnabled(false);
        editarBtn.setEnabled(false);
        producionBtn.setEnabled(false);
        verInfoAccidentadoBtn.setVisible(false);
        verInfoIncapacitadoBtn.setVisible(false);

    }

    private void btnEnable() {
        incapacitadoCheck.setEnabled(true);
        accidentadoCheck.setEnabled(true);
        editarBtn.setEnabled(true);
        verInfoAccidentadoBtn.setVisible(true);
        verInfoIncapacitadoBtn.setVisible(true);
        String rol = (String) tablaProduccion.getValueAt(tablaProduccion.getSelectedRow(), 6);
        if (rol.equalsIgnoreCase("cochero")) {
            producionBtn.setEnabled(true);

        }
    }

    private int cedulaSelect() {
        String cedula = (String) tablaProduccion.getValueAt(tablaProduccion.getSelectedRow(), 0);
        
        return Integer.parseInt(cedula);
    }

    private int minaSelect() {
        String mina = (String) tablaProduccion.getValueAt(tablaProduccion.getSelectedRow(), 9);
        mina = mina.substring(0, 1);
        return Integer.parseInt(mina);
    }

    private void borrarRegistros() {
        try {
            modelo.setNumRows(0);
            tablaProduccion.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }

    }

    private void buscarPersona() {
        ArrayList personal = Persona.consultarPorNombre(buscarTxt.getText());

        String[] cols = new String[]{"CEDULA", "NOMBRE", "APELLIDO", "F NACIMIENTO", "GENERO", "ESTADO", "ROL", "USUARIO", "CLAVE", "MINA"};

        modelo.setColumnIdentifiers(cols);

        for (int i = 0; i < personal.size(); i++) {
            modelo.addRow((Object[]) personal.get(i));
//            String id = (String) tablaProduccion.getValueAt(i, 9);
//            System.out.println(id);
//            ArrayList<String> datMin = Mina.consultar(Integer.parseInt(id));
//            modelo.setValueAt(datMin.get(1), i, 9);
        }
        tablaProduccion.setModel(modelo);
    }

    private void buscarProduccion() {
        int idMina = filPorMina();

        ArrayList rows = Produccion.consultarPorMina(idMina);

        String[] cols = new String[]{"FECHA", "CANTIDAD", "CEDULA", "MINA"};

        modelo.setColumnIdentifiers(cols);
        tablaProduccion.setModel(modelo);
        for (int i = 0; i < rows.size(); i++) {
            modelo.addRow((Object[]) rows.get(i));
        }
    }

    private void buscarPersonaPorMina() {
        int idMina = filPorMina();
        ArrayList personal = Persona.consultarPersonaporMina(idMina);

        String[] cols = new String[]{"CEDULA", "NOMBRE", "APELLIDO", "F NACIMIENTO", "GENERO", "ESTADO", "ROL", "USUARIO", "CLAVE", "MINA"};

        modelo.setColumnIdentifiers(cols);

        for (int i = 0; i < personal.size(); i++) {
            modelo.addRow((Object[]) personal.get(i));
            System.out.println(i);
        }
        tablaProduccion.setModel(modelo);

    }

    private void buscarAccidentadosPorMina() {
        int idMina = filPorMina();
        ArrayList personal = Accidentado.consultarAccidentadoPorMina(idMina);

        String[] cols = new String[]{"ID_ACCIDENTADO", "FECHA", "DESCRIPCION", "CEDULA"};

        modelo.setColumnIdentifiers(cols);

        for (int i = 0; i < personal.size(); i++) {
            modelo.addRow((Object[]) personal.get(i));
            System.out.println(i);
        }
        tablaProduccion.setModel(modelo);

    }

    private void buscarIncapacitadosPorMina() {
        int idMina = filPorMina();
        ArrayList personal = Incapacidad.consultarIncapacitadoPorMina(idMina);

        String[] cols = new String[]{"ID_INCAPACIDAD", "FECHA", "TIPO", "FECHA_FIN", "REEMPLAZADO", "CEDULA"};

        modelo.setColumnIdentifiers(cols);

        for (int i = 0; i < personal.size(); i++) {
            modelo.addRow((Object[]) personal.get(i));
            System.out.println(i);
        }
        tablaProduccion.setModel(modelo);

    }

    private void informeAccidentePersona() {
        acci.setNumRows(0);
        tabAcc.setModel(acci);
        String rol = (String) tablaProduccion.getValueAt(tablaProduccion.getSelectedRow(), 0);

        ArrayList info = Accidentado.consultarAccidentadoPorPersona(Integer.parseInt(rol));

        String[] cols = new String[]{"ID_ACCIDENTADO", "FECHA", "DESCRIPCION", "CEDULA"};

        acci.setColumnIdentifiers(cols);

        for (int i = 0; i < info.size(); i++) {
            acci.addRow((Object[]) info.get(i));

        }
        tabAcc.setModel(acci);

        JOptionPane.showMessageDialog(null, tabAcc);
    }

    private void informeIncapacidadPersona() {
        acci.setNumRows(0);
        tabAcc.setModel(acci);
        String rol = (String) tablaProduccion.getValueAt(tablaProduccion.getSelectedRow(), 0);

        ArrayList info = Incapacidad.consultarIncapacidadPorPersona(Integer.parseInt(rol));

        String[] cols = new String[]{"ID_INCAPACIDAD", "FECHA", "TIPO", "FECHA_FIN", "REEMPLAZADO", "CEDULA"};

        acci.setColumnIdentifiers(cols);

        for (int i = 0; i < info.size(); i++) {
            acci.addRow((Object[]) info.get(i));

        }
        tabAcc.setModel(acci);

        JOptionPane.showMessageDialog(null, tabAcc);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio(1, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox accidentadoCheck;
    private javax.swing.JMenuItem accidentadosMenu;
    private javax.swing.JMenuItem agregarMinaMenu;
    private javax.swing.JMenuItem agregarPersonaMenu;
    private javax.swing.JCheckBox autoCheck;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JButton editarBtn;
    private javax.swing.JCheckBox incapacitadoCheck;
    private javax.swing.JMenuItem incapacitadosMenu;
    private javax.swing.JMenu informesMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuAgregar;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTabbedPane panelAgregar;
    private javax.swing.JMenuItem personalMenu;
    private javax.swing.JMenuItem produccionMenu;
    private javax.swing.JButton producionBtn;
    private javax.swing.JTextField rolTxt;
    private javax.swing.JTable tablaProduccion;
    private javax.swing.JTextField usuarioTxt;
    private javax.swing.JButton verInfoAccidentadoBtn;
    private javax.swing.JButton verInfoIncapacitadoBtn;
    // End of variables declaration//GEN-END:variables
}
